version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      # Pin compatible versions
      - echo "flask==2.0.3" > requirements.txt
      - echo "werkzeug==2.0.3" >> requirements.txt
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Starting Flask app..."
      # Run in foreground with explicit bind
      - python flask-app.py --host=0.0.0.0 --port=5000 &
      - sleep 10  # Extra time to start
      - curl -v http://localhost:5000
      - pkill -f "python flask-app.py"
