version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "flask==2.0.3" > requirements.txt
      - echo "werkzeug==2.0.3" >> requirements.txt
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Starting Flask app..."
      # Run on port 3000 to match your app's configuration
      - python flask-app.py --host=0.0.0.0 --port=3000 &
      - sleep 10
      # Test the correct port (3000)
      - curl -v http://localhost:3000
      - pkill -f "python flask-app.py"

  post_build:
    commands:
      - echo "Build completed successfully"
