version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      # Create requirements.txt with Flask
      - echo "flask==2.0.1" > requirements.txt
      # Install dependencies
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Testing Flask app..."
      # Run your actual file (flask-app.py)
      - python flask-app.py &                # Background process
      - sleep 5                             # Increased wait time
      - curl http://localhost:5000          # Test endpoint
      - pkill -f "python flask-app.py"      # Cleanup
